# Generated by Django 4.2.7 on 2024-01-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0002_blog_poster_alter_blog_category_alter_blog_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Пост', 'verbose_name_plural': 'Пости'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категорія', 'verbose_name_plural': 'Категорії'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='poster',
            field=models.URLField(default='http://placehold.it/100x100', verbose_name='Постер'),
        ),
    ]
