# Generated by Django 4.2.7 on 2024-01-16 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0003_alter_blog_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
